spring:
  datasource:
    url: jdbc:h2:mem:mydb
    jpa:
      hibernate:
        ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show_sql: true

logging:
  level:
    root: info