server:
  port: 8101

spring:
  application:
    name: site-management-system-java-backend
  profiles:
    active: ${PROFILE:local}
  datasource:
    username: ${db_username}
    password: ${db_password}
    driverClassName: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    show_sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

logging:
  level:
    root: error